name: Android Build

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Setup Java JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'gradle'
        
    - name: Install Android SDK
      uses: android-actions/setup-android@v3
      with:
        api-level: 33
        build-tools: 33.0.0
        target: default
        
    - name: Build web assets
      run: npm run build
      
    - name: Add Android platform
      run: npx cap add android
      
    - name: Sync web assets to Android
      run: npx cap sync android
      
    - name: Build Android APK (Debug)
      run: |
        cd android
        chmod +x ./gradlew
        ./gradlew assembleDebug
        
    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: zodiac-search-debug-apk
        path: android/app/build/outputs/apk/debug/app-debug.apk
        retention-days: 30
        
    - name: Build Android APK (Release)
      run: |
        cd android
        chmod +x ./gradlew
        ./gradlew assembleRelease
        
    - name: Upload Release APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: zodiac-search-release-apk
        path: android/app/build/outputs/apk/release/app-release.apk
        retention-days: 30
        
  # 可选的发布作业 - 仅在推送标签时运行
  release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - name: Download APK artifacts
      uses: actions/download-artifact@v4
      with:
        pattern: zodiac-search-*-apk
        
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: zodiac-search-*-apk/*.apk
        draft: false
        prerelease: false
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
